### ISSUE TITLE
Alfred 3 warning

### ISSUE THREAD

**Issue by luxxi** [DONSA/alfred-google-translate#1]
Changing the settings (targetLanguage) caused a warning (attached image).
I found out the path to Alfred is hard coded in workflows.php and I fixed the Alfred version from 2 to 3 and it worked. The better way will be by using script environment variables: alfred_workflow_cache and alfred_workflow_data.

<img width="332" alt="1f210c1c-eb23-11e6-922c-3747eeae207b" src="https://cloud.githubusercontent.com/assets/1362438/22628603/15dc52d8-ebd7-11e6-86b4-eb9d11b69108.png">

**Comment by DONSA** [comment]
Just fixed the cache path for Alfred 3. Take a look.

**Comment by luxxi** [comment]
It's working now. Wouldn't be better to use script environment variables alfred_workflow_cache and alfred_workflow_data to prevent the same issue happen again? I'm not familiar with building workflows, just searched for these two variables that could replace hard coded Alfred path.

**Comment by DONSA** [comment]
Yeah, makes sense. I included in v3.3.
