### ISSUE TITLE
Support for entry with dots

### ISSUE THREAD

**Issue by AnthoPakPak** [DONSA/alfred-google-translate#12]
Hey, thanks for your fork :) 

Do you think it would be possible to add support for queries containing dots ? Currently if I try to convert this text with `gt en` :

`Mollis dolor est purus curae, himenaeos condimentum sed. Sociis facilisis praesent arcu feugiat porta molestie congue. Nullam at mi etiam parturient mollis lobortis cursus.`

It returns : 

`Soft consumer is still a concern, but himenaeos sauce.`

So it seems to split on first dot. I would really like to translate a complete paragraph, it would be awesome.

Thanks in advance :)

**Comment by DONSA** [comment]
Thanks for pointing out the issue. Fixed in the last release.

**Comment by AnthoPakPak** [comment]
Thanks a lot for your reactivity ! 👏
