### ISSUE TITLE
target auto and source auto didn't work

### ISSUE THREAD

**Issue by Nevu** [DONSA/alfred-google-translate#13]
Hey!

I use this workflow very much, thank you for creating this. But I got an issue:

I'd like to have it like this: I typing something in german OR in english and he will automatically show the right translation (english OR german). Or it would be great to have a list of more translations f.e. german, french, english. gtset target auto, gtset source auto seems not to work ...

Can I make this setup?

**Comment by DONSA** [comment]
Hi,

If I understand correctly, you want to be able to translate from any language into fixed set of languages.
To accomplish that you can leave source as automatic and set your target languages which, in this case, would be the command `gtset target de,fr,en`.
Then you just need to **⇧+⌘+g** (or any other hotkey you set) and start typing.

<img width="634" alt="screenshot 2018-12-22 at 1 28 45 pm" src="https://user-images.githubusercontent.com/4755300/50374391-906d9700-05ed-11e9-9ecc-7770d82264f7.png">

**Comment by Nevu** [comment]
Hey,
I'm sorry – there was a problem with my google-key. Now it works the way you told :)

**Comment by DONSA** [comment]
Perfect!
