### ISSUE TITLE
Danish flag (dk.png) not displayed (instead unknown.png)

### ISSUE THREAD

**Issue by gandalfsaxe** [DONSA/alfred-google-translate#14]
The Danish flag (`src/icons/dk.png`) does not show up, but instead just the generic does (src/icons/unknown.png`).

<img width="623" alt="image" src="https://user-images.githubusercontent.com/12127864/54871086-eeee1100-4da6-11e9-8d6e-42850e60ca60.png">

I also noticed that some flag filenames is the country name, others is the language code. They should probably be standardized. Let me know if I can help in any way.

**Comment by DONSA** [comment]
I renamed the flag to correct ISO code and exported the workflow again.
Thanks for pointing out.

**Comment by gandalfsaxe** [comment]
Thanks, appreciated 👍
