### ISSUE TITLE
Keyword gt cuts first word (translate works correctly)

### ISSUE THREAD

**Issue by gandalfsaxe** [DONSA/alfred-google-translate#15]
First word is cut off using `gt` but not `translate`:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/12127864/54879222-50a58e00-4e2e-11e9-819e-be290d322f8e.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/12127864/54879224-526f5180-4e2e-11e9-9bcd-2ce9081d69af.png">

**Comment by DONSA** [comment]
Small bug in script filter. Fixed now.
