### ISSUE TITLE
Order of target languages randomly connected to order of output?

### ISSUE THREAD

**Issue by gandalfsaxe** [DONSA/alfred-google-translate#16]
It seems strange that this order of garget languages: es,da,en

<img width="623" alt="image" src="https://user-images.githubusercontent.com/12127864/54879418-ac711680-4e30-11e9-9e0b-ac9486acf493.png">

Results in the output order of: en,es,da:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/12127864/54879428-c4e13100-4e30-11e9-9646-30b07a5da605.png">

The ordering is not even the same with one permutation, so I'm not sure what's going on here 🙂

**Comment by DONSA** [comment]
Didn't take translation order into consideration but, in theory, it should have the same order as the config file. I will take look at this one when I have time.

**Comment by DONSA** [comment]
Last version (3.6.0) now includes [uid](https://www.alfredapp.com/help/workflows/inputs/script-filter/xml/#helpcontent) identifier on each option that allows Alfred to automatically sort results based on most frequent choices.
It makes more sense this way IMO.

**Comment by gandalfsaxe** [comment]
So no manual control? I think most users have an idea of which order they would like when using multiple languages 🙂

**Comment by DONSA** [comment]
By default is the order is the one configs are set. Then it will be sorted by frequent choices.
If you want the order to be always the one configs are set, create a pull request with that option and I will merge it.
