### ISSUE TITLE
gtset source and target not working

### ISSUE THREAD

**Issue by riki-dexter** [DONSA/alfred-google-translate#19]
Hi @DONSA , thank you for this great workflow.
`gtset source` and `gtset target` are not working for me, still getting `Warning: require_once(GoogleTranslateSettingWorkflow.php): failed to open stream`.
Thank you.

**Comment by DONSA** [comment]
Thanks for reporting. Is fixed now. You can update it.

**Comment by riki-dexter** [comment]
Can you update repository source code?
Thank you

**Comment by DONSA** [comment]
It is updated.
