### ISSUE TITLE
Proxy connection

### ISSUE THREAD

**Issue by riki-dexter** [DONSA/alfred-google-translate#20]
Hi @DONSA ,
thank you for #19 immediate fix!
I have a question: I have a proxy connection that returns this error calling Google Translate service: `Fatal error: Uncaught ErrorException: cURL error 7: Failed to connect to translate.google.com port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in [...]/Alfred.alfredpreferences/workflows/user.workflow.F3A7597C-05FB-4C43-B53D-D602842FA234/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php:294`
Is there any way to let it work?
A manual cURL to new Google Cloud Translate API with my API key (`https://translation.googleapis.com/language/translate/v2?key=[...]`), for example, is working also with this proxy.
Thank you

**Comment by DONSA** [comment]
I'm using `stichoza/google-translate-php` library which uses Guzzle for HTTP requests.
He has a method on his library called `setHttpOption` that allows you to pass a proxy [configuration](http://docs.guzzlephp.org/en/latest/request-options.html#proxy) that will be used by Guzzle every time a request is made.

**Comment by riki-dexter** [comment]
And this configuration can be passed to the workflow that set it on Guzzle?

**Comment by DONSA** [comment]
No, you will need to change it in the code.
Basically when `TranslateClient` class is instantiated you need to call that `setHttpOption` method and pass the proxy option.
Of course you can make it configurable but that requires extra work on the workflow.

**Comment by riki-dexter** [comment]
Ok, thank you.
