### ISSUE TITLE
Icons not loading correctly

### ISSUE THREAD

**Issue by benknight** [DONSA/alfred-google-translate#21]
Great workflow however the icons for a lot of languages are not correctly loaded in the script filter's feedback XML.

It's a pretty simple issue here: https://github.com/DONSA/alfred-google-translate/blob/master/src/GoogleTranslateWorkflow.php#L175

Taking Vietnamese for example, the ISO code is "vi" so the icon file needs to be named vi.png (not vietnam.png).  Solution is to rename all the icon files to use their ISO codes.

**Comment by benknight** [comment]
Also worth considering, is mapping flags to languages can in some cases be awkward.  Taking English as an example, seeing a union jack is more closely related to the concept of the United Kingdom itself than the English language.  Some flags can be considered politically sensitive as well.  So an easy solution to the above issue might just be doing away with flag icons altogether.  You could show an image with the ISO lang code instead possibly.

**Comment by DONSA** [comment]
Most of the flags were not renamed to the correct ISO code. Vietnam was changed now in 38a3533.

**Comment by benknight** [comment]
Thanks for the quick response.  The issue was not only the Vietnam flag however, there are a number of other languages with the same problem.  Korean for example.

**Comment by DONSA** [comment]
Please give me a list of the ones you want to use or create a PR.
