### ISSUE TITLE
In afred 3 is invalid, is there any way to maintain Google api prohibiting unauthorized clients from calling Google's translation interface?

### ISSUE THREAD

**Issue by fuuqiu** [DONSA/alfred-google-translate#24]
In afred 3 is invalid, is there any way to maintain Google api prohibiting unauthorized clients from calling Google's translation interface?

**Comment by DONSA** [comment]
Can you show the error you are getting?

**Comment by fuuqiu** [comment]
![WeChat11f9e10b9ecf68dc92e9981bd4a8d5be](https://user-images.githubusercontent.com/35496061/60855120-1e7d3800-a235-11e9-9289-49174f106feb.png)
Nothing happens, can you use it now?

**Comment by DONSA** [comment]
This should be working on Alfred 3. Make sure you have the latest workflow version.

Open Alfred preferences, select Google Translate workflow, click on the debug button (the little bug icon on top right corner) and select the 'All information' option from the dropdown.
Then do the same action you have shown and paste here the output from that console.

![Screenshot 2019-07-09 at 11 18 31 AM](https://user-images.githubusercontent.com/4755300/60876020-58513d00-a23b-11e9-9ac9-5d75c05a8479.png)

**Comment by fuuqiu** [comment]
[17:56:57.097] Logging Started...
[17:57:03.379] Google Translate[Hotkey] Processing complete
[17:57:03.381] Google Translate[Hotkey] Passing output '' to Script Filter
[17:57:37.724] Google Translate[Hotkey] Processing complete
[17:57:37.729] Google Translate[Hotkey] Passing output '' to Script Filter
[17:57:38.736] Google Translate[Script Filter] Queuing argument 'gt auto>pt Text to translate'
[17:58:05.133] Google Translate[Script Filter] Queuing argument 'auto>pt Text to translate'

**Comment by fuuqiu** [comment]
Is it because I am in China, is the reason why google network service is not available? Is it necessary to configure the network proxy, my laptop can access http://www.google.com through the configuration agent?

**Comment by DONSA** [comment]
It is possible to do a request using a proxy but the workflow is not prepared for that.

**Comment by fuuqiu** [comment]
Sorry, my version is alfred 4.0. The reason for the failure is not a web proxy, because I have configured the alfred web proxy, but using `gt Text to translate` is still no response.

**Comment by DONSA** [comment]
I can see it's an intermittent issue. I will take a look once I have time.

**Comment by fuuqiu** [comment]
Ok, thank you very much, google service needs to be configured in some areas to use, look forward to your update

**Comment by DONSA** [comment]
Fixed on ee25ed8. Please update it.

**Comment by chenshengzhi** [comment]
How can i change `translate.google.com` to `translate.google.cn`?

**Comment by DONSA** [comment]
Open the project in the terminal and run `grep -rnw "translate.google.com" .`
You will find the files that you need to change.
Next time create a new issue, this one is closed.

**Comment by chenshengzhi** [comment]
OK, thank you.
