### ISSUE TITLE
What is the last version which supports Alfred 3?

### ISSUE THREAD

**Issue by IanVS** [DONSA/alfred-google-translate#26]
I tried installing this workflow, but I only have Alfred 3 and I'm seeing this message in the workflow settings page:

![image](https://user-images.githubusercontent.com/4616705/70851578-c7733300-1e64-11ea-9205-08fb5a4083da.png)

Is there a version of this plugin which works for Alfred 3?

**Comment by DONSA** [comment]
It's not supported.

**Comment by IanVS** [comment]
Maybe you could add a note to the readme?
