### ISSUE TITLE
Cannot set target language (error: read only)

### ISSUE THREAD

**Issue by gandalfsaxe** [DONSA/alfred-google-translate#28]
when I try:

`gtset target en,es,da`

debug output:

```
Warning: file_put_contents(/config.json): failed to open stream: Read-only file system in /Users/gandalf/Documents/-sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.120C8D96-8FFD-4412-9E92-426A72F7788F/src/GoogleTranslateWorkflowBase.php on line 63
target set to en,es,da' to Post Notification
```

![image](https://user-images.githubusercontent.com/12127864/75254572-dbca9900-57e0-11ea-8b86-387ad2c0b35d.png)

**Comment by gandalfsaxe** [comment]
I downloaded and ran a fresh copy of the workflow btw

**Comment by gandalfsaxe** [comment]
Input: `ls -la`

Output:
```
total 88
drwxr-xr-x@  10 gandalf  staff    320 Jan  6 13:50 .
drwxr-xr-x   11 gandalf  staff    352 Feb 25 15:04 ..
-rw-r--r--@   1 gandalf  staff    913 May 12  2019 AlfredResult.php
-rw-r--r--@   1 gandalf  staff   1110 May 12  2019 AlfredResultItem.php
-rw-r--r--@   1 gandalf  staff   3989 May 12  2019 GoogleTranslateSettingsWorkflow.php
-rw-r--r--@   1 gandalf  staff   5693 Jul 10  2019 GoogleTranslateWorkflow.php
-rw-r--r--@   1 gandalf  staff   1649 Jan  6 13:50 GoogleTranslateWorkflowBase.php
-rw-r--r--@   1 gandalf  staff   2363 May 12  2019 Languages.php
```

**Comment by gandalfsaxe** [comment]
Ran `chmod 0777 GoogleTranslateWorkflowBase.php`

Input: `ls -la`

Output:
```
total 88
drwxr-xr-x@  10 gandalf  staff    320 Jan  6 13:50 .
drwxr-xr-x   11 gandalf  staff    352 Feb 25 15:04 ..
-rw-r--r--@   1 gandalf  staff    913 May 12  2019 AlfredResult.php
-rw-r--r--@   1 gandalf  staff   1110 May 12  2019 AlfredResultItem.php
-rw-r--r--@   1 gandalf  staff   3989 May 12  2019 GoogleTranslateSettingsWorkflow.php
-rw-r--r--@   1 gandalf  staff   5693 Jul 10  2019 GoogleTranslateWorkflow.php
-rwxrwxrwx@   1 gandalf  staff   1649 Jan  6 13:50 GoogleTranslateWorkflowBase.php
-rw-r--r--@   1 gandalf  staff   2363 May 12  2019 Languages.php
-rw-r--r--@   1 gandalf  staff  13090 May 12  2019 Workflows.php
drwxr-xr-x@ 266 gandalf  staff   8512 Dec 12 15:49 icons
```

**Comment by DONSA** [comment]
Try to run `touch ./config.json` inside that folder and set the languages again.
If it doesn't work try to add write permissions to that same file (0666 should be enough).

**Comment by gandalfsaxe** [comment]
I did this, but still get:
```
Warning: file_put_contents(/config.json): failed to open stream: Read-only file system in /Users/gandalf/Documents/-sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.120C8D96-8FFD-4412-9E92-426A72F7788F/src/GoogleTranslateWorkflowBase.php on line 63
target set to en,es,da' to Post Notification
```

I tried again but don't get three languages:
![image](https://user-images.githubusercontent.com/12127864/75400503-bbddc700-58ff-11ea-956f-711aad984c0e.png)

**Comment by DONSA** [comment]
I thought that the config file was on the project folder but no, it's on Alfred's cache folder.
Try to do the same inside `~/Library/Application Support/Alfred/Workflow Data/scriptme.alfred.googletranslate/config.json`.
Your permissions are probably messed up on that directory.

**Comment by gandalfsaxe** [comment]
Still same :/

> Warning: file_put_contents(/config.json): failed to open stream: Read-only file system in /Users/gandalf/Documents/-sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.120C8D96-8FFD-4412-9E92-426A72F7788F/src/GoogleTranslateWorkflowBase.php on line 63
target set to en,es,da' to Post Notification
```

**Comment by frufru666** [comment]
I'm experiencing the same issue. Did you find a solution as the issue has been closed?

**Comment by gandalfsaxe** [comment]
Nope I ended up using Google Translate in a pinned tab instead.
