### ISSUE TITLE
Country flag incorrect

### ISSUE THREAD

**Issue by shirohana** [DONSA/alfred-google-translate#3]
Excuse me,
I found the flag of Taiwan was be instead with the flag of China.

![2017-06-27 12 29 38](https://user-images.githubusercontent.com/11359892/27550212-6f3b75c0-5ad1-11e7-8867-6fc596cb7830.png)

https://www.countryflags.com/en/taiwan-flag-vector.html

Hope you help to fix up this mistake (´；ω；｀)

**Comment by DONSA** [comment]
Please provide flag with same size and style and I will replace it.

**Comment by shirohana** [comment]
This reply comes so late that I even forgot this issue (ㆆᴗㆆ)

**Comment by shirohana** [comment]
There's already one `taiwan.png` inside your project, just replace it `taiwan.png -> zh-tw.png`

https://github.com/DONSA/alfred-google-translate/blob/master/src/icons/taiwan.png

**Comment by DONSA** [comment]
Yesterday I was fixing some bugs and I notice this open issue.
This bug and other issues I've found are fixed now, you can update the workflow.
