### ISSUE TITLE
Min amount of letters to translate

### ISSUE THREAD

**Issue by avxkim** [DONSA/alfred-google-translate#7]
Hello, is it possible to set minimal amount of letter to 2, not 3?

**Comment by DONSA** [comment]
Sure, change from 3 to 2 in:
https://github.com/DONSA/alfred-google-translate/blob/master/src/GoogleTranslateWorkflow.php#L23

**Comment by avxkim** [comment]
Can you change it in your repo? Or even make it as a variable?

**Comment by DONSA** [comment]
Create a PR, I will merge it.

**Comment by avxkim** [comment]
How to recompile `google-translate.alfredworkflow` so it will reflect the changes to a php files?

**Comment by DONSA** [comment]
Right click and then `Export...`

<img width="523" alt="screenshot 2018-10-17 at 6 14 34 pm" src="https://user-images.githubusercontent.com/4755300/47100791-9b482c00-d238-11e8-8815-bb1f1c0c1e32.png">

**Comment by avxkim** [comment]
Didn't get it, lol. Let me explain, I forked this repo, added changes, how can I import updated workflow with changes in php files?

**Comment by DONSA** [comment]
You are one step behind. Click `Open in Finder` replace changed files and then export the workflow.

**Comment by avxkim** [comment]
Then exported workflow upload in repo?

**Comment by DONSA** [comment]
Exactly.

**Comment by avxkim** [comment]
I'll PR again with KK language.

**Comment by avxkim** [comment]
please, merge this #11
